title: Lewis Fredericks - Handcrafted Horn Eyewear
author: Finn Lawrence
description: Lewis Fredericks Eyewear offers time-honoured silhouettes fashioned from horn, the previously wasted by-product of domesticated Buffalo, Ram and Ox.
baseurl: ""
collections:
  frames: {}
  stockists: {}
  lookbooks: {}